I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "game/screens.rpy", line 303, in set_default
    default quick_menu = True
Exception: store.quick_menu is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "/Users/isaacadel/Desktop/EPFL/BA6/Jeu video et gamification/renpy-8.0.3-sdk/renpy/ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/isaacadel/Desktop/EPFL/BA6/Jeu video et gamification/renpy-8.0.3-sdk/renpy/python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "/Users/isaacadel/Desktop/EPFL/BA6/Jeu video et gamification/renpy-8.0.3-sdk/renpy/exports.py", line 3797, in execute_default_statement
    i.set_default(start)
  File "game/screens.rpy", line 303, in set_default
    default quick_menu = True
Exception: store.quick_menu is being given a default a second time.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
Emperio 1.0
Tue May  2 15:07:24 2023
