I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 87, in script
    python :
  File "game/script.rpy", line 88, in <module>
    renpy.jump(list_scenario.pop(0))
NameError: name 'list_scenario' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 87, in script
    python :
  File "/Users/isaacadel/Desktop/EPFL/BA6/Jeu video et gamification/renpy-8.0.3-sdk/renpy/ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/isaacadel/Desktop/EPFL/BA6/Jeu video et gamification/renpy-8.0.3-sdk/renpy/python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 88, in <module>
    renpy.jump(list_scenario.pop(0))
NameError: name 'list_scenario' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
Emperio 1.0
Tue May  2 13:11:19 2023
